### ISSUE TITLE
Support für "Unifi Video"

### ISSUE THREAD

**Issue by Systm21** [peterbaumert/ioBroker.unifi-protect#12]
Hallo *,
ist es möglich, dass die selbstgehoste Variante von "Unifi Protect", nämlich "Unifi Video" mit zu supporten? Scheinbar geht das im moment noch nicht, da im Log eine Fehlermeldung bezüglich Login auftaucht (obwohl definitiv richtig).

Grüße

**Comment by peterbaumert** [comment]
Das geht leider nicht, da es dort keine (mir bekannte) api gibt.
