### ISSUE TITLE
Fehler bei motion

### ISSUE THREAD

**Issue by daendaen** [peterbaumert/ioBroker.unifi-protect#15]
Object unifi-protect.0.motions.5f6cf04702d03c03e7000411 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"

Kann jemand bitte weiterhelfen?

VG

**Comment by peterbaumert** [comment]
Hast du mal versucht den adapter zu stoppen, einmal unter objekte alles zu löschen und wieder zu starten?

**Comment by peterbaumert** [comment]
keine rückmeldung
