### ISSUE TITLE
Einrichtung des Adapters in Home & Status Code 404

### ISSUE THREAD

**Issue by DJCA666** [peterbaumert/ioBroker.unifi-protect#48]
Guten Tag Herr Baumert, 

Ich hatte Ihren Adapter auf der Hoobs Homebridge installiert da ich diesen in IOBroker nicht fand und war damit äußerst zufrieden. Dies war auch relativ einfach. 

Jetzt habe ich es Geschafft (bin Laie 😅) die Beta ihres Adapters in den IOBoker zu bekommen, aber hab keine Ahnung was ich machen muss um die Kameras in Home zu sehen.... 

Bei Hoobs musste ich lediglich den QR Code scannen um es in Home hinzuzufügen, wie funktioniert das über den Broker? Ich danke ihnen vielmals und hoffe ich bin hier mit meinem Anliegen richtig...! Ebenso hoffe ich dieses Mal alles richtig gemacht zu haben, es ist mein zweiter Eintrag auf Git und ich bin neu, seid bitte nachsichtig mit mir 😅

**Versions:**  
 - Adapter version: 0.0.12
 - JS-Controller version: 5.2.8
 - Node version: 12.22.2
 - Operating system: IOBroker & RaspberryPi 4

**Comment by DJCA666** [comment]
Ach und ganz vergessen, bei mir ist der Adapter auch Grün egal was ich auch falsch eingegeben habe (hab die IP's des NVR und des CK's versucht und die Ports probiert).

**Comment by DJCA666** [comment]
Irgendjemand der mir helfen kann....?

**Comment by DJCA666** [comment]
Ist das standard das man auf Git keine Antworten bekommt? Bei aller Hochachtung für die Arbeit, aber das ist ja echt positiv für Entwickler und Adapter....

**Comment by peterbaumert** [comment]
Hallo erstmal,

also bzgl git und der Antwortgeschwindigkeit darfst du halt nicht vergessen, dass die Adapter eigentlich alle in ihrer Freizeit bauen. Und ich war z.b. 3 Wochen in Urlaub und dann erstmal wieder auf der Arbeit genug zu tun. Ist halt "Best Effort" hier...

ja das mit "Home" nehme mal an IOS hat mit dem Adapter nichts zu tun. Da müsste man bei yahka oder soetwas schauen. Am einfachste ist es allerdings den https://github.com/ioBroker/ioBroker.ham zu installieren und dort dann "unifi-protect"

Habe ham im "Local Mode" laufen.
